export const actionsTypes = {
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  LOADING: 'LOADING',
  GET_DECK_ID: 'GET_DECK_ID',
  GET_CARDS: 'GET_CARDS',
  GET_DECK_FAIL: 'GET_DECK_FAIL',
};
