export const actionsTypes = {
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  LOADING: 'LOADING',
  SET_STEP: 'SET_STEP',
  GET_DECK_ID: 'GET_DECK_ID',
  GET_CARDS: 'GET_CARDS',
  GET_DECK_FAIL: 'GET_DECK_FAIL',
  SAVE_PILES: 'SAVE_PILES',
};
